providers = ["...", "python"]

[phases.setup]
nixPkgs = ["...", "git", "wget", "curl", "gnupg", "gettext", "gcc", "pkg-config", "typst"]
nixLibs = ["...", "libpq", "zlib", "libjpeg"]

[phases.install]
cmds = ["...", "pipenv sync --deploy"]

[phases.build]
cmds = [
  "python3 install_plugins.py",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind :$PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.13"
PYTHONUNBUFFERED = "1"         # (provider sets this by default too)
PYTHONDONTWRITEBYTECODE = "1"  # (provider sets this by default too)
PIPENV_VENV_IN_PROJECT = "1"
