# Generated by Django 5.1.4 on 2025-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0055_alter_resourcecategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequestprescription',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
