# Generated by Django 5.1.4 on 2025-09-14 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0056_medicationrequestprescription_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequestprescription',
            name='alternate_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='medicationrequestprescription',
            constraint=models.UniqueConstraint(fields=('alternate_identifier', 'encounter'), name='unique_alternate_identifier_encounter'),
        ),
    ]
