# Generated by Django 5.1.4 on 2025-09-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0058_alter_medicationrequestprescription_prescribed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationdispense',
            old_name='authorizing_prescription',
            new_name='authorizing_request',
        ),
    ]
