# Generated by Django 5.1.4 on 2025-09-14 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0059_rename_authorizing_prescription_medicationdispense_authorizing_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequestprescription',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
