# Generated by Django 5.1.4 on 2025-09-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0055_alter_invoice_total_gross_alter_invoice_total_net'),
        ('emr', '0060_medicationrequestprescription_tags'),
    ]

    operations = [
    ]
