name: Generate SBOM

on: 
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pipenv install --dev

      - name: Install CycloneDX Python tool
        run: pip install cyclonedx-bom

      - name: Generate verbose SBOM
        run: cyclonedx-py pipenv --output-format json --output-file sbom.json --verbose --include-dev

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
          if-no-files-found: error
